spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/merchant
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123qwe
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
          initial-size: 30
          max-total: 50
          max-idle: 10
          min-idle: 5
          max-wait-millis: 200